// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPecHg3N5DzfFqN26Om5VlsYowFRrzDMw',
    appId: '1:1033977571916:web:38a54e1d2477e8feebe2e9',
    messagingSenderId: '1033977571916',
    projectId: 'test-b7fa4',
    authDomain: 'test-b7fa4.firebaseapp.com',
    storageBucket: 'test-b7fa4.firebasestorage.app',
    measurementId: 'G-VY22L69CFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDss4pqN6CRg7ruLC9Nsu4Y2-odRADMTts',
    appId: '1:1033977571916:android:09704797087d7d5debe2e9',
    messagingSenderId: '1033977571916',
    projectId: 'test-b7fa4',
    storageBucket: 'test-b7fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJWMjj85UzhrmyWIe7F3QyMjgOeNGcqU',
    appId: '1:1033977571916:ios:7a0b5d1a9cca56caebe2e9',
    messagingSenderId: '1033977571916',
    projectId: 'test-b7fa4',
    storageBucket: 'test-b7fa4.firebasestorage.app',
    iosBundleId: 'com.example.rapiddtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvJWMjj85UzhrmyWIe7F3QyMjgOeNGcqU',
    appId: '1:1033977571916:ios:7a0b5d1a9cca56caebe2e9',
    messagingSenderId: '1033977571916',
    projectId: 'test-b7fa4',
    storageBucket: 'test-b7fa4.firebasestorage.app',
    iosBundleId: 'com.example.rapiddtask',
  );
}
